"""
=============================================================================
OTT Product & User Analytics - Streamlit Interactive Reporting Dashboard
=============================================================================
Architecture:
Database (SQLite) -> SQL Queries -> Python/Pandas -> Analysis CSV Tables -> Streamlit Dashboard

This dashboard reads the pre-computed analysis tables generated by the SQL pipeline.
=============================================================================
"""

import os
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# -----------------------------------------------------------------------------
# 1. Page Configuration & Custom Theme
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="OTT Product & User Analytics | JioStar Simulation",
    page_icon="🎬",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom Styling for clean OTT Analytics theme
st.markdown("""
<style>
    .main-title {
        font-size: 2.2rem;
        font-weight: 700;
        color: #1E293B;
        margin-bottom: 0px;
    }
    .sub-title {
        font-size: 1.05rem;
        color: #64748B;
        margin-bottom: 20px;
    }
    .metric-card {
        background-color: #F8FAFC;
        border-radius: 8px;
        padding: 16px;
        border-left: 4px solid #0284C7;
        box-shadow: 0 1px 3px rgba(0,0,0,0.05);
    }
    .insight-box {
        background-color: #F0F9FF;
        border-left: 4px solid #0284C7;
        padding: 14px 18px;
        border-radius: 6px;
        margin-top: 15px;
        margin-bottom: 15px;
        color: #0369A1;
        font-weight: 500;
    }
    .recommendation-card {
        background-color: #FFFFFF;
        border: 1px solid #E2E8F0;
        border-radius: 8px;
        padding: 18px;
        margin-bottom: 12px;
        box-shadow: 0 1px 2px rgba(0,0,0,0.03);
    }
</style>
""", unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# 2. Data Loading & Caching Layer
# -----------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(BASE_DIR, "analysis_results")
RAW_DATA_PATH = os.path.join(BASE_DIR, "data", "raw_data.csv")

@st.cache_data
def load_analysis_tables():
    """Load pre-aggregated SQL analysis tables."""
    df_users = pd.read_csv(os.path.join(RESULTS_DIR, "user_insights.csv"))
    df_content = pd.read_csv(os.path.join(RESULTS_DIR, "content_insights.csv"))
    df_genre = pd.read_csv(os.path.join(RESULTS_DIR, "genre_insights.csv"))
    df_device = pd.read_csv(os.path.join(RESULTS_DIR, "device_insights.csv"))
    df_region = pd.read_csv(os.path.join(RESULTS_DIR, "region_insights.csv"))
    df_engagement = pd.read_csv(os.path.join(RESULTS_DIR, "engagement_insights.csv"))
    df_experiment = pd.read_csv(os.path.join(RESULTS_DIR, "experiment_insights.csv"))
    return df_users, df_content, df_genre, df_device, df_region, df_engagement, df_experiment

@st.cache_data
def load_raw_data():
    """Load raw event log for fine-grained interactive filtering."""
    if os.path.exists(RAW_DATA_PATH):
        return pd.read_csv(RAW_DATA_PATH)
    return pd.DataFrame()

try:
    df_users, df_content, df_genre, df_device, df_region, df_engagement, df_experiment = load_analysis_tables()
    df_raw = load_raw_data()
except Exception as e:
    st.error(f"Error loading analysis tables: {e}. Please run `python src/analysis.py` first.")
    st.stop()

# -----------------------------------------------------------------------------
# 3. Sidebar Filters
# -----------------------------------------------------------------------------
st.sidebar.image("https://img.icons8.com/fluency/96/video-playlist.png", width=64)
st.sidebar.title("OTT Filters & Controls")
st.sidebar.markdown("Filter playback events across catalog dimensions:")

# Genre Filter
all_genres = ["All"] + sorted(df_content["genre"].dropna().unique().tolist())
selected_genre = st.sidebar.selectbox("Filter by Genre", all_genres)

# Language Filter
all_languages = ["All"] + sorted(df_content["language"].dropna().unique().tolist())
selected_language = st.sidebar.selectbox("Filter by Language", all_languages)

# Device Filter
all_devices = ["All"] + sorted(df_device["device"].dropna().unique().tolist())
selected_device = st.sidebar.selectbox("Filter by Device", all_devices)

# City Filter
all_cities = ["All"] + sorted(df_region["city"].dropna().unique().tolist())
selected_city = st.sidebar.selectbox("Filter by City", all_cities)

# Subscription Plan Filter
all_plans = ["All"] + sorted(df_users["subscription_plan"].dropna().unique().tolist())
selected_plan = st.sidebar.selectbox("Filter by Plan", all_plans)

st.sidebar.markdown("---")
st.sidebar.info(
    "💡 **Analytics Architecture**\n"
    "• Raw Events → SQLite DB\n"
    "• SQL Execution → Pandas\n"
    "• Analysis Tables → Streamlit"
)

# Apply Filters to Raw Data for interactive metrics
filtered_raw = df_raw.copy()
if selected_genre != "All":
    filtered_raw = filtered_raw[filtered_raw["genre"] == selected_genre]
if selected_language != "All":
    filtered_raw = filtered_raw[filtered_raw["language"] == selected_language]
if selected_device != "All":
    filtered_raw = filtered_raw[filtered_raw["device"] == selected_device]
if selected_city != "All":
    filtered_raw = filtered_raw[filtered_raw["city"] == selected_city]
if selected_plan != "All":
    filtered_raw = filtered_raw[filtered_raw["subscription_plan"] == selected_plan]

# Filter content table
filtered_content = df_content.copy()
if selected_genre != "All":
    filtered_content = filtered_content[filtered_content["genre"] == selected_genre]
if selected_language != "All":
    filtered_content = filtered_content[filtered_content["language"] == selected_language]

# Filter user table
filtered_users = df_users.copy()
if selected_city != "All":
    filtered_users = filtered_users[filtered_users["city"] == selected_city]
if selected_plan != "All":
    filtered_users = filtered_users[filtered_users["subscription_plan"] == selected_plan]

# -----------------------------------------------------------------------------
# 4. Header & KPI Metrics
# -----------------------------------------------------------------------------
st.markdown('<div class="main-title">🎬 OTT Product & User Analytics</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-title">SQL-driven analysis of OTT viewing behavior • Inspired by JioStar / JioHotstar Analytics</div>', unsafe_allow_html=True)

# Dynamic Top-Level Metrics
col1, col2, col3, col4, col5 = st.columns(5)

total_users_count = len(filtered_users)
total_views_count = len(filtered_raw)
total_watch_hours = round(filtered_raw["watch_duration"].sum() / 60.0, 1) if not filtered_raw.empty else 0.0
avg_session_mins = round(filtered_raw["watch_duration"].mean(), 1) if not filtered_raw.empty else 0.0
completion_rate = round((filtered_raw["completed"].sum() / total_views_count) * 100.0, 1) if total_views_count > 0 else 0.0

col1.metric("👥 Active Users", f"{total_users_count:,}")
col2.metric("▶️ Total Views", f"{total_views_count:,}")
col3.metric("⏱️ Watch Time", f"{total_watch_hours:,} hrs")
col4.metric("📊 Avg Session", f"{avg_session_mins} mins")
col5.metric("🎯 Completion Rate", f"{completion_rate}%")

st.markdown("---")

# -----------------------------------------------------------------------------
# 5. Main Navigation Tabs
# -----------------------------------------------------------------------------
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "📊 Content & Genre Insights",
    "👥 User & Engagement Insights",
    "📱 Device & Region Analysis",
    "🧪 A/B Experiment Analysis",
    "💡 Business Strategy & Insights"
])

# -----------------------------------------------------------------------------
# TAB 1: Content & Genre Insights
# -----------------------------------------------------------------------------
with tab1:
    st.subheader("1. Most Viewed Content")
    
    top_content_table = filtered_content[[
        "content_title", "genre", "language", "content_type", "total_views", "avg_watch_minutes", "completion_rate_pct"
    ]].head(10).rename(columns={
        "content_title": "Content Title",
        "genre": "Genre",
        "language": "Language",
        "content_type": "Format",
        "total_views": "Total Views",
        "avg_watch_minutes": "Avg Watch (min)",
        "completion_rate_pct": "Completion Rate (%)"
    })
    st.dataframe(top_content_table, use_container_width=True, hide_index=True)
    
    st.markdown("---")
    st.subheader("2. Genre Performance")
    
    col_g1, col_g2 = st.columns(2)
    
    with col_g1:
        # Genre vs Number of Views
        fig_genre_views = px.bar(
            df_genre,
            x="genre",
            y="total_views",
            title="Total Views by Genre",
            labels={"genre": "Genre", "total_views": "Number of Views"},
            color="total_views",
            color_continuous_scale="Blues"
        )
        fig_genre_views.update_layout(showlegend=False)
        st.plotly_chart(fig_genre_views, use_container_width=True)
        
    with col_g2:
        # Genre vs Average Watch Duration
        fig_genre_watch = px.bar(
            df_genre,
            x="genre",
            y="avg_watch_duration_minutes",
            title="Average Watch Duration by Genre (Minutes)",
            labels={"genre": "Genre", "avg_watch_duration_minutes": "Avg Watch Mins"},
            color="avg_watch_duration_minutes",
            color_continuous_scale="Teal"
        )
        fig_genre_watch.update_layout(showlegend=False)
        st.plotly_chart(fig_genre_watch, use_container_width=True)
        
    # Dynamic Data-Driven Insight
    top_duration_genre = df_genre.sort_values(by="avg_watch_duration_minutes", ascending=False).iloc[0]
    top_views_genre = df_genre.sort_values(by="total_views", ascending=False).iloc[0]
    
    st.markdown(
        f'<div class="insight-box">💡 <b>Content Insight:</b> <b>{top_views_genre["genre"]}</b> generates the highest total volume ({top_views_genre["total_views"]:,} views), while <b>{top_duration_genre["genre"]}</b> commands the highest average viewer stickiness with <b>{top_duration_genre["avg_watch_duration_minutes"]} minutes</b> per session.</div>',
        unsafe_allow_html=True
    )
    
    # Language & Content Type Analysis
    col_l1, col_l2 = st.columns(2)
    with col_l1:
        lang_summary = df_raw.groupby("language")["event_id"].count().reset_index()
        lang_summary.columns = ["Language", "Views"]
        lang_summary = lang_summary.sort_values(by="Views", ascending=False)
        fig_lang = px.pie(
            lang_summary,
            names="Language",
            values="Views",
            title="Audience Language Share",
            hole=0.4,
            color_discrete_sequence=px.colors.qualitative.Safe
        )
        st.plotly_chart(fig_lang, use_container_width=True)
        
    with col_l2:
        type_summary = df_content.groupby("content_type")["total_views"].sum().reset_index()
        type_summary.columns = ["Format", "Views"]
        fig_type = px.bar(
            type_summary.sort_values(by="Views", ascending=True),
            x="Views",
            y="Format",
            orientation="h",
            title="Views by Content Format (Shows vs Sports vs Movies)",
            color="Views",
            color_continuous_scale="Viridis"
        )
        st.plotly_chart(fig_type, use_container_width=True)


# -----------------------------------------------------------------------------
# TAB 2: User & Engagement Insights
# -----------------------------------------------------------------------------
with tab2:
    st.subheader("1. Most Active Users (Power Streamers)")
    
    top_users_table = filtered_users.sort_values(by="total_watch_minutes", ascending=False).head(10)[[
        "user_id", "city", "subscription_plan", "age_group", "total_sessions", "total_watch_minutes", "avg_watch_minutes_per_session"
    ]].rename(columns={
        "user_id": "User ID",
        "city": "City",
        "subscription_plan": "Plan",
        "age_group": "Age Cohort",
        "total_sessions": "Sessions",
        "total_watch_minutes": "Total Watch Time (min)",
        "avg_watch_minutes_per_session": "Avg per Session (min)"
    })
    st.dataframe(top_users_table, use_container_width=True, hide_index=True)
    
    st.markdown("---")
    
    col_u1, col_u2 = st.columns(2)
    with col_u1:
        # Age Group Viewing Behavior
        age_summary = df_users.groupby("age_group").agg({
            "total_watch_minutes": "mean",
            "total_sessions": "mean"
        }).reset_index()
        age_summary.columns = ["Age Group", "Avg Watch Mins", "Avg Sessions"]
        
        fig_age = px.bar(
            age_summary,
            x="Age Group",
            y="Avg Watch Mins",
            title="Average Watch Minutes by Age Cohort",
            color="Avg Watch Mins",
            color_continuous_scale="Purples"
        )
        st.plotly_chart(fig_age, use_container_width=True)
        
    with col_u2:
        # Subscription Plan Engagement
        plan_summary = df_users.groupby("subscription_plan").agg({
            "total_watch_minutes": "mean",
            "user_id": "count"
        }).reset_index()
        plan_summary.columns = ["Plan", "Avg Watch Mins", "User Count"]
        
        fig_plan = px.bar(
            plan_summary,
            x="Plan",
            y="Avg Watch Mins",
            title="Average Watch Time by Subscription Plan",
            color="Plan",
            color_discrete_map={"Free": "#94A3B8", "VIP": "#38BDF8", "Premium": "#0284C7"}
        )
        st.plotly_chart(fig_plan, use_container_width=True)
        
    st.markdown("---")
    st.subheader("2. User Engagement Tiers (High vs Medium vs Low)")
    
    col_t1, col_t2 = st.columns([1, 1])
    with col_t1:
        st.dataframe(
            df_engagement.rename(columns={
                "user_engagement_tier": "Engagement Tier",
                "total_users": "Users",
                "user_percentage": "Share (%)",
                "avg_watch_minutes": "Avg Watch (min)",
                "avg_sessions": "Avg Sessions"
            }),
            use_container_width=True,
            hide_index=True
        )
    with col_t2:
        fig_tiers = px.pie(
            df_engagement,
            names="user_engagement_tier",
            values="total_users",
            title="Platform User Engagement Distribution",
            color_discrete_sequence=["#0284C7", "#38BDF8", "#CBD5E1"]
        )
        st.plotly_chart(fig_tiers, use_container_width=True)

    # Dynamic user insight
    high_tier = df_engagement[df_engagement["user_engagement_tier"].str.contains("High")].iloc[0]
    st.markdown(
        f'<div class="insight-box">💡 <b>User Retention Insight:</b> <b>{high_tier["user_percentage"]}%</b> of users are High Engagement power users consuming an average of <b>{high_tier["avg_watch_minutes"]} minutes</b>. Re-engagement notification strategies should target the Low Engagement cohort to prevent churn.</div>',
        unsafe_allow_html=True
    )


# -----------------------------------------------------------------------------
# TAB 3: Device & Region Analysis
# -----------------------------------------------------------------------------
with tab3:
    col_d1, col_d2 = st.columns(2)
    
    with col_d1:
        st.subheader("📱 Device Performance")
        st.dataframe(
            df_device[[
                "device", "total_views", "view_share_pct", "avg_watch_duration_minutes", "completion_rate_pct"
            ]].rename(columns={
                "device": "Device",
                "total_views": "Views",
                "view_share_pct": "Share (%)",
                "avg_watch_duration_minutes": "Avg Watch (min)",
                "completion_rate_pct": "Completion (%)"
            }),
            use_container_width=True,
            hide_index=True
        )
        
        fig_device = px.bar(
            df_device,
            x="device",
            y="total_views",
            title="Total Views by Device Form Factor",
            color="device",
            color_discrete_sequence=px.colors.qualitative.Prism
        )
        st.plotly_chart(fig_device, use_container_width=True)
        
    with col_d2:
        st.subheader("🌆 Regional Performance (Top Cities)")
        st.dataframe(
            df_region[[
                "city", "state", "total_views", "avg_watch_duration_minutes", "completion_rate_pct"
            ]].head(6).rename(columns={
                "city": "City",
                "state": "State",
                "total_views": "Views",
                "avg_watch_duration_minutes": "Avg Watch (min)",
                "completion_rate_pct": "Completion (%)"
            }),
            use_container_width=True,
            hide_index=True
        )
        
        fig_region = px.bar(
            df_region.sort_values(by="total_views", ascending=True),
            x="total_views",
            y="city",
            orientation="h",
            title="Viewing Volume Across Cities",
            color="total_views",
            color_continuous_scale="Blues"
        )
        st.plotly_chart(fig_region, use_container_width=True)

    # Dynamic Device / Region insight
    top_device = df_device.iloc[0]
    highest_watch_device = df_device.sort_values(by="avg_watch_duration_minutes", ascending=False).iloc[0]
    top_city = df_region.iloc[0]
    
    st.markdown(
        f'<div class="insight-box">💡 <b>Device & Geo Insight:</b> <b>{top_device["device"]}</b> drives maximum traffic volume ({top_device["view_share_pct"]}% share), but <b>{highest_watch_device["device"]}</b> delivers the longest uninterrupted sessions (<b>{highest_watch_device["avg_watch_duration_minutes"]} mins</b>). <b>{top_city["city"]}</b> is the top-performing regional market with <b>{top_city["total_views"]:,} views</b>.</div>',
        unsafe_allow_html=True
    )


# -----------------------------------------------------------------------------
# TAB 4: A/B Experiment Analysis
# -----------------------------------------------------------------------------
with tab4:
    st.subheader("🧪 A/B Experiment: Personalized Content Tray V2 vs Default Feed")
    st.markdown("Analysis of randomized Control vs Treatment groups evaluating the impact of an AI-driven personalized recommendation row on the home screen.")
    
    # Display Experiment Summary Table
    st.dataframe(
        df_experiment.rename(columns={
            "group_name": "Group",
            "total_users": "Users",
            "total_sessions": "Total Sessions",
            "avg_sessions_per_user": "Sessions / User",
            "total_watch_minutes": "Total Watch Time (min)",
            "avg_watch_duration_per_user": "Avg Watch / User (min)",
            "avg_watch_minutes_per_session": "Avg Watch / Session (min)",
            "completion_rate_pct": "Completion Rate (%)"
        }),
        use_container_width=True,
        hide_index=True
    )
    
    ctrl = df_experiment[df_experiment["group_name"] == "Control"].iloc[0]
    trt = df_experiment[df_experiment["group_name"] == "Treatment"].iloc[0]
    
    # Dynamic calculations
    watch_uplift = round(((trt["avg_watch_duration_per_user"] - ctrl["avg_watch_duration_per_user"]) / ctrl["avg_watch_duration_per_user"]) * 100.0, 2)
    session_uplift = round(((trt["avg_sessions_per_user"] - ctrl["avg_sessions_per_user"]) / ctrl["avg_sessions_per_user"]) * 100.0, 2)
    comp_uplift = round(((trt["completion_rate_pct"] - ctrl["completion_rate_pct"]) / ctrl["completion_rate_pct"]) * 100.0, 2)
    
    ecol1, ecol2, ecol3 = st.columns(3)
    ecol1.metric("⏱️ Watch Duration Uplift", f"{watch_uplift:+.2f}%", delta=f"{watch_uplift}%")
    ecol2.metric("🔄 Session Frequency Uplift", f"{session_uplift:+.2f}%", delta=f"{session_uplift}%")
    ecol3.metric("🎯 Completion Rate Uplift", f"{comp_uplift:+.2f}%", delta=f"{comp_uplift}%")
    
    col_exp_chart1, col_exp_chart2 = st.columns(2)
    with col_exp_chart1:
        fig_exp_watch = px.bar(
            df_experiment,
            x="group_name",
            y="avg_watch_duration_per_user",
            title="Avg Watch Duration per User (Control vs Treatment)",
            color="group_name",
            color_discrete_map={"Control": "#94A3B8", "Treatment": "#0284C7"}
        )
        st.plotly_chart(fig_exp_watch, use_container_width=True)
        
    with col_exp_chart2:
        fig_exp_comp = px.bar(
            df_experiment,
            x="group_name",
            y="completion_rate_pct",
            title="Completion Rate % (Control vs Treatment)",
            color="group_name",
            color_discrete_map={"Control": "#94A3B8", "Treatment": "#10B981"}
        )
        st.plotly_chart(fig_exp_comp, use_container_width=True)
        
    st.markdown("### 📋 Product Analyst Interpretation & Next Steps")
    st.info(
        f"**Key Finding:** The Treatment group demonstrated a **{watch_uplift}% increase** in average watch duration per user and a **{comp_uplift}% boost** in video completion rate.\n\n"
        "**Product Recommendation:** The Personalized Content Tray successfully reduces discovery friction and boosts viewer engagement. "
        "Recommend proceeding to a staged 50% → 100% platform-wide rollout while monitoring server load and video startup time."
    )


# -----------------------------------------------------------------------------
# TAB 5: Business Strategy & Insights
# -----------------------------------------------------------------------------
with tab5:
    st.subheader("💡 Strategic Product & Business Recommendations")
    st.markdown("Synthesized insights from SQL database queries translated into concrete OTT product strategies:")
    
    # 1. Content Curation
    st.markdown(f"""
    <div class="recommendation-card">
        <h4>1. 🏆 Double Down on Sports & Drama Content Hubs</h4>
        <p><b>Data Evidence:</b> Sports and Drama together account for over <b>{round((df_genre[df_genre['genre'].isin(['Sports', 'Drama'])]['total_views'].sum() / df_genre['total_views'].sum()) * 100, 1)}%</b> of platform views with strong session duration.</p>
        <p><b>Strategic Action:</b> Create dedicated Live Match hub pages and prime-time Drama carousel banners to maximize organic viewer acquisition during key sporting seasons (e.g. IPL, ICC tournaments).</p>
    </div>
    """, unsafe_allow_html=True)
    
    # 2. Regional Expansion
    top_langs = df_content.groupby("language")["total_views"].sum().sort_values(ascending=False).head(3).index.tolist()
    st.markdown(f"""
    <div class="recommendation-card">
        <h4>2. 🗺️ Regional Language Catalog Expansion ({', '.join(top_langs)})</h4>
        <p><b>Data Evidence:</b> Regional markets ({', '.join(df_region['city'].head(3).tolist())}) exhibit heavy appetite for regional language content (Tamil, Telugu, Bengali) with high completion rates.</p>
        <p><b>Strategic Action:</b> Invest in localized audio dubbing and regional original series to accelerate subscriber penetration in Tier-2 and regional markets.</p>
    </div>
    """, unsafe_allow_html=True)
    
    # 3. Large-Screen TV Experience
    st.markdown(f"""
    <div class="recommendation-card">
        <h4>3. 📺 Optimize Large-Screen (Smart TV) Lean-Back Experience</h4>
        <p><b>Data Evidence:</b> Smart TV users have the highest session duration (<b>{df_device[df_device['device']=='Smart TV']['avg_watch_duration_minutes'].iloc[0]} mins</b>) and highest completion rates.</p>
        <p><b>Strategic Action:</b> Improve Smart TV UI auto-play next episode cues, 4K HDR playback stability, and household multi-profile switcher to drive living room retention.</p>
    </div>
    """, unsafe_allow_html=True)
    
    # 4. Churn Prevention
    low_eng_pct = df_engagement[df_engagement['user_engagement_tier'].str.contains('Low')]['user_percentage'].iloc[0]
    st.markdown(f"""
    <div class="recommendation-card">
        <h4>4. 🔔 Targeted Re-Engagement for Low-Activity Segment</h4>
        <p><b>Data Evidence:</b> <b>{low_eng_pct}%</b> of users are in the low-engagement tier (< 100 minutes total watch time).</p>
        <p><b>Strategic Action:</b> Implement personalized push notifications triggering when a user's favored genre has a new release or match start, driving dormant users back into active playback.</p>
    </div>
    """, unsafe_allow_html=True)
    
    # 5. Full Rollout of Personalized Recommendations
    st.markdown(f"""
    <div class="recommendation-card">
        <h4>5. 🚀 Full Rollout of Personalized Homepage Trays</h4>
        <p><b>Data Evidence:</b> A/B testing verified a <b>+{watch_uplift}%</b> watch duration uplift and <b>+{session_uplift}%</b> session frequency increase for the Treatment variant.</p>
        <p><b>Strategic Action:</b> Progressively ramp the recommendation tray to 100% of the active user base across mobile and web platforms.</p>
    </div>
    """, unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# Footer
# -----------------------------------------------------------------------------
st.markdown("---")
st.caption("OTT Product & User Analytics Project | Portfolio & Interview Preparation for JioStar / JioHotstar Analytics")
